(https://en.wikipedia.org/wiki/Regular_expression)
We will use regular expressions for parsing text files. (https://en.wikipedia.org/wiki/Regular_expression)

The process for parsing is as follows - 
1.   Find a unique pattern for the start of parsing segment
2.   Find a pattern for the end of segment
1.   Read the file
2.   Look for the line with start pattern
1.   Starting the parsing code until end pattern is encountered

Use this for testing regular expression (https://regex101.com/)

In [4]:
import re

In [31]:
# we will parse the mulliken charges from tddft gaussion output

# find the pattern
start_pattern = re.compile(r'Mulliken charges:')

In [32]:
# end pattern
end_pattern = re.compile(r'Sum of Mulliken charges')

In [33]:
# read the output file
# read the file (I prefer to read lines as list of lines)

with open("tddft.log") as f:
    lines = f.readlines()

In [34]:
# check types
print("the type of lines variable is ", type(lines))

the type of lines variable is  <class 'list'>

In [35]:
# first 10 lines
print(lines[:10])

[' Entering Gaussian System, Link 0=g16\n', ' Input=tddft.com\n', ' Output=tddft.log\n', ' Initial command:\n', ' /g16/l1.exe "/Gau-348183.inp" -scrdir="/tddfttoluene/"\n', ' Entering Link 1 = /g16/l1.exe PID=    348184.\n', '  \n', ' Copyright (c) 1988,1990,1992,1993,1995,1998,2003,2009,2016,\n', '            Gaussian, Inc.  All Rights Reserved.\n', '  \n']

In [36]:
# we will use re.match( to check whether the lines contains our start pattern

for idx , line in enumerate(lines): # loops over lines
    if re.match(start_pattern, line.strip()):
        break
        
print(idx)

1401

In [37]:
# parse lines (first two lines are not needed)
# line.strip() --> gets rid of empty spaces

idx = idx +2
line = lines[idx]

parsed_lines = []
while not(re.match(end_pattern, line.strip())):
    parsed_lines.append(line.strip())
    idx += 1
    line = lines[idx]

In [38]:
# parsed data
print(parsed_lines)

['1  C   -0.465360', '2  C   -0.010817', '3  C    0.014265', '4  C   -0.067333', '5  C   -0.066472', '6  C   -0.017958', '7  C   -0.066472', '8  C   -0.067333', '9  C   -0.017847', '10  H    0.097434', '11  C   -0.063162', '12  C    0.014265', '13  C   -0.017846', '14  C   -0.017958', '15  C   -0.062534', '16  H    0.096142', '17  C   -0.062535', '18  C   -0.010816', '19  H    0.096142', '20  H    0.097434', '21  C   -0.063163', '22  H    0.093636', '23  H    0.093636', '24  C   -0.465361', '25  H    0.093854', '26  H    0.093854', '27  Si   0.902314', '28  C   -0.498137', '29  C   -0.502107', '30  C   -0.498140', '31  Si   0.902315', '32  C   -0.502106', '33  C   -0.498136', '34  C   -0.498142', '35  H    0.109584', '36  H    0.105333', '37  H    0.109597', '38  H    0.111110', '39  H    0.108326', '40  H    0.104419', '41  H    0.111110', '42  H    0.104419', '43  H    0.108324', '44  H    0.108319', '45  H    0.104422', '46  H    0.111114', '47  H    0.109586', '48  H    0.109595', '49  H    0.105334', '50  H    0.111114', '51  H    0.104422', '52  H    0.108317']

In [43]:
# testing on one line
parsed_lines[0].strip().split()

['1', 'C', '-0.465360']

In [44]:
# creting the dictionary for better visualization

clean_line = parsed_lines[0].strip().split()

d = {"number": int(clean_line[0]),
     "atom": clean_line[1],
     "charge": float(clean_line[2])
    }
print(d)

{'number': 1, 'atom': 'C', 'charge': -0.46536}

In [50]:
# clean up data

data = []
for line in parsed_lines:
    clean_line = line.strip().split()
    data.append({"number": int(clean_line[0]),
     "atom": clean_line[1],
     "charge": float(clean_line[2])
    })

In [65]:
# crating a table with pandas
import pandas as pd
pd.DataFrame(data)

    number atom    charge
0        1    C -0.465360
1        2    C -0.010817
2        3    C  0.014265
3        4    C -0.067333
4        5    C -0.066472
5        6    C -0.017958
6        7    C -0.066472
7        8    C -0.067333
8        9    C -0.017847
9       10    H  0.097434
10      11    C -0.063162
11      12    C  0.014265
12      13    C -0.017846
13      14    C -0.017958
14      15    C -0.062534
15      16    H  0.096142
16      17    C -0.062535
17      18    C -0.010816
18      19    H  0.096142
19      20    H  0.097434
20      21    C -0.063163
21      22    H  0.093636
22      23    H  0.093636
23      24    C -0.465361
24      25    H  0.093854
25      26    H  0.093854
26      27   Si  0.902314
27      28    C -0.498137
28      29    C -0.502107
29      30    C -0.498140
30      31   Si  0.902315
31      32    C -0.502106
32      33    C -0.498136
33      34    C -0.498142
34      35    H  0.109584
35      36    H  0.105333
36      37    H  0.109597
37      38    H  0.111110
38      39    H  0.108326
39      40    H  0.104419
40      41    H  0.111110
41      42    H  0.104419
42      43    H  0.108324
43      44    H  0.108319
44      45    H  0.104422
45      46    H  0.111114
46      47    H  0.109586
47      48    H  0.109595
48      49    H  0.105334
49      50    H  0.111114
50      51    H  0.104422
51      52    H  0.108317